import type { Metadata } from "next";
import {ReactNode} from "react";
import { Inter } from "next/font/google";
import "../globals.css";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';
import DynamicUI from "../components/layout/DynamicUI";
import NavbarLeft from "../components/layout/navbarLeft";
import { layoutSizes } from "../const_store";
import CopyrightFooter from "../components/layout/small_UI_elements/copyrightFooter";



const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

interface LocaleLayoutProps {
  children?: ReactNode;
}

export const metadata: Metadata = {
  title: "ICV",
  description: "Generated by AI-DAVis Dashboard members...",
  icons: {
    icon: {
      url: "/icon.svg",
      type: "image/svg",
    },
  },
};

export default async function LocaleLayout({ children}: LocaleLayoutProps) {


 
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  const locale = await getLocale();



  return (
    <html lang={locale} >
      <body className={`${inter.className} overflow-y-scroll overflow-x-clip bg-surface-default`} suppressHydrationWarning={true}>
      <NextIntlClientProvider messages={messages}>
         
         {/* Wrap all pages in the layout with the dynamicUI (navbars etc.)
          ToDo: get rid of wrapping everything into a client component "DynamicUI"
          Problem: all is now CSR and no SSR is possible
          Goal: allow SSR for "children"
         */}
         <DynamicUI layoutSizes = {layoutSizes}>
           <main>
            {children}
          </main>
          <CopyrightFooter textColor="#000000"/>
        </DynamicUI>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}