name: Cleanup Old Package Versions

on:
  workflow_dispatch: # Allows manual execution from the Actions tab
  #schedule:
  #  - cron: '0 0 * * 0' # Executed automatically every Sunday at midnight

jobs:
  delete-versions:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      # 1. Cleanup Frontend Versions Safely
      - name: Clean up icv-frontend
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: icv-frontend
          keep-n-tagged: 3
          delete-untagged: true

      # 2. Cleanup Database Versions Safely
      - name: Clean up icv-database
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: icv-database
          keep-n-tagged: 3
          delete-untagged: true

      # 3. Cleanup Backend Versions Safely
      - name: Clean up icv-backend
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: icv-backend
          keep-n-tagged: 3
          delete-untagged: true

      # 4. Cleanup PgBouncer Versions Safely
      - name: Clean up icv-pgbouncer
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: icv-pgbouncer
          keep-n-tagged: 3
          delete-untagged: true